### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by bkw** [sous-chefs/thor-foodcritic#6]
A new release for the foodcritic-4.0 support would be awesome!

**Comment by wjimenez5271** [comment]
I assume this is why I get the following error when trying to use this gem with foodcritic 4.0:
```
/Library/Ruby/Gems/2.0.0/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:46:in `check': wrong number of arguments (2 for 0..1) (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/thor-foodcritic-0.2.0/lib/thor-foodcritic.rb:30:in `lint'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/runner.rb:36:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/bin/thor:6:in `<top (required)>'
	from /usr/bin/thor:23:in `load'
	from /usr/bin/thor:23:in `<main>'
```

**Comment by trinitronx** [comment]
Same result with `foodcritic 5.0.0`:

```
be thor foodcritic:lint
/Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/gems/foodcritic-5.0.0/lib/foodcritic/linter.rb:69:in `check': wrong number of arguments (2 for 0..1) (ArgumentError)
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/gems/thor-foodcritic-0.2.0/lib/thor-foodcritic.rb:30:in `lint'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/gems/thor-0.19.1/lib/thor/runner.rb:36:in `method_missing'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/gems/thor-0.19.1/bin/thor:6:in `<top (required)>'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/bin/thor:23:in `load'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/bin/thor:23:in `<main>'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/bin/ruby_executable_hooks:15:in `eval'
  from /Users/jcuzella/.rvm/gems/ruby-2.2.2@test_gemset/bin/ruby_executable_hooks:15:in `<main>'
```

It looks like there was a PR to fix this bug in #5, but no new release was cut at this point.  Since then, `foodcritic` gem has pushed onward and has left `thor-foodcritic` in the dust.

For those weary travelers who still have `thor-foodcritic` (and perhaps also `guard-foodcritic`) in their `Gemfile`s... here is a set of compatible gems (Note: `growl` and `guard` related gems are optional if you only want `thor-foodcritic` and `foodcritic` working):

```
source 'https://rubygems.org'

group :task_runners do
  gem 'thor-foodcritic', :github => 'reset/thor-foodcritic', :ref => 'e38a99d539ff39ea2dfd6f4719ecc547c51d1a08'
  gem 'rake'
end

group :lint do
  gem 'foodcritic', '~> 4.0'
#  gem 'rubocop', '~> 0.34' # Too strict & not pragmatic... Bleh!
end

group :development do
  gem 'ruby_gntp'
  gem 'growl'
  gem 'rb-fsevent'
  gem 'guard', '~> 2.4'
  gem 'guard-kitchen'
  gem 'guard-foodcritic', '~> 1.1.1'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'mixlib-versioning'
end
```

**Comment by adamb-altiscale** [comment]
+1 on this, would be great to do. Any word?

**Comment by tas50** [comment]
2.0 is out with the foodcritic version constraint removed!
